[project]
name = "travel-assistant"
version = "0.1.0"
description = "AI-powered travel assistant with user memory and monitoring"
requires-python = ">=3.11"

dependencies = [
    "psycopg2-binary>=2.9.10",
    "requests>=2.32.5",
    "streamlit>=1.49.1",
]
