# Streamlit Secrets Configuration
# This file contains sensitive configuration data for Streamlit Cloud
# Copy this file and replace the placeholder values with your actual credentials

# Database Configuration (Neon PostgreSQL)
DB_HOST = "ep-hidden-rain-adlq7a8p-pooler.c-2.us-east-1.aws.neon.tech"
DB_PORT = "5432"
DB_NAME = "travel_assistant"
DB_USER = "neondb_owner"
DB_PASSWORD = "npg_5uoSBbv0TgDK"
DB_SSLMODE = "require"

# Groq API Configuration
GROQ_API_KEY = "your-groq-api-key-here"